export const projects = [
  {
    title: "Let's Play",
    image: "/images/lets-play.png",
    description: "Application de gestion d'événements et de jeux en ligne.",
    techStack: ["Next.js", "NestJS", "MongoDB", "Socket.io", "Tailwind CSS"],
    repoLink: "https://github.com/amran-zak/lets-play-frontend",
    backendRepo: "https://github.com/amran-zak/lets-play-backend",
    demoLink: "https://lets-play-ynov.netlify.app/",
    isPrivate: true,
  },
  {
    title: "Cine-App",
    image: "/images/cine-app.png",
    description: "Application de recommandation de films et séries.",
    techStack: ["Vue.js", "Node.js", "Express", "MongoDB"],
    repoLink: "https://github.com/amran-zak/cine-app",
    demoLink: "https://cine-app-ynov.netlify.app/",
  },
  {
    title: "MonColis",
    image: "/images/moncolis.png",
    description: "Plateforme de gestion et suivi de colis en temps réel.",
    techStack: ["React.js", "Node.js", "Express", "MongoDB", "Redux"],
    repoLink: "https://github.com/amran-zak/MonColisFront",
    backendRepo: "https://github.com/amran-zak/moncolis_back",
    demoLink: "https://mon-colis.netlify.app/",
    isPrivate: true,
  },
  {
    title: "Petite Annonce",
    image: "/images/petite-annonce.png",
    description: "Site d'annonces en ligne avec système de messagerie.",
    techStack: ["TypeScript", "React.js", "Firebase"],
    repoLink: "https://github.com/amran-zak/Petite-annonce",
    backendRepo: "https://github.com/amran-zak/Petite-annonce",
    demoLink: "https://petite-annonce.netlify.app/",
  },
  {
    title: "Chat-App Ydays",
    image: "/images/chat-app.png",
    description: "Application de messagerie instantanée en temps réel.",
    techStack: ["React.js", "Firebase", "WebSockets"],
    repoLink: "https://github.com/amran-zak/chat-app-ydays",
    demoLink: "https://chat-app-yday.web.app/login",
  },
  {
    title: "TP-Movies-BDD",
    image: "/images/tp-movies.png", // Mets une vraie image si dispo
    description: "Projet de base de données pour la gestion de films.",
    techStack: ["Angular", "PostgreSQL", "Node.js"],
    repoLink: "https://github.com/NkwamoMaeva/TP-Movies-BDD",
    demoLink: "#",
  },
];
